using Microsoft.EntityFrameworkCore.Migrations;

namespace Netatmo.Dashboard.Data.Migrations
{
    public partial class AddCountryEntityWithSeedingFromRestCountries : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Countries",
                columns: table => new
                {
                    Code = table.Column<string>(fixedLength: true, maxLength: 2, nullable: false),
                    Flag = table.Column<string>(maxLength: 40, nullable: false),
                    NameEN = table.Column<string>(maxLength: 256, nullable: false),
                    NameBR = table.Column<string>(maxLength: 256, nullable: true),
                    NamePT = table.Column<string>(maxLength: 256, nullable: true),
                    NameNL = table.Column<string>(maxLength: 256, nullable: true),
                    NameHR = table.Column<string>(maxLength: 256, nullable: true),
                    NameFA = table.Column<string>(maxLength: 256, nullable: true),
                    NameDE = table.Column<string>(maxLength: 256, nullable: true),
                    NameES = table.Column<string>(maxLength: 256, nullable: true),
                    NameFR = table.Column<string>(maxLength: 256, nullable: true),
                    NameJA = table.Column<string>(maxLength: 256, nullable: true),
                    NameIT = table.Column<string>(maxLength: 256, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Countries", x => x.Code);
                });

            migrationBuilder.InsertData(
                table: "Countries",
                columns: new[] { "Code", "Flag", "NameBR", "NameDE", "NameEN", "NameES", "NameFA", "NameFR", "NameHR", "NameIT", "NameJA", "NameNL", "NamePT" },
                values: new object[,]
                {
                    { "AF", "https://restcountries.eu/data/afg.svg", "Afeganistão", "Afghanistan", "Afghanistan", "Afganistán", "افغانستان", "Afghanistan", "Afganistan", "Afghanistan", "アフガニスタン", "Afghanistan", "Afeganistão" },
                    { "NC", "https://restcountries.eu/data/ncl.svg", "Nova Caledônia", "Neukaledonien", "New Caledonia", "Nueva Caledonia", "کالدونیای جدید", "Nouvelle-Calédonie", "Nova Kaledonija", "Nuova Caledonia", "ニューカレドニア", "Nieuw-Caledonië", "Nova Caledónia" },
                    { "NZ", "https://restcountries.eu/data/nzl.svg", "Nova Zelândia", "Neuseeland", "New Zealand", "Nueva Zelanda", "نیوزیلند", "Nouvelle-Zélande", "Novi Zeland", "Nuova Zelanda", "ニュージーランド", "Nieuw-Zeeland", "Nova Zelândia" },
                    { "NI", "https://restcountries.eu/data/nic.svg", "Nicarágua", "Nicaragua", "Nicaragua", "Nicaragua", "نیکاراگوئه", "Nicaragua", "Nikaragva", "Nicaragua", "ニカラグア", "Nicaragua", "Nicarágua" },
                    { "NE", "https://restcountries.eu/data/ner.svg", "Níger", "Niger", "Niger", "Níger", "نیجر", "Niger", "Niger", "Niger", "ニジェール", "Niger", "Níger" },
                    { "NG", "https://restcountries.eu/data/nga.svg", "Nigéria", "Nigeria", "Nigeria", "Nigeria", "نیجریه", "Nigéria", "Nigerija", "Nigeria", "ナイジェリア", "Nigeria", "Nigéria" },
                    { "NU", "https://restcountries.eu/data/niu.svg", "Niue", "Niue", "Niue", "Niue", "نیووی", "Niue", "Niue", "Niue", "ニウエ", "Niue", "Niue" },
                    { "NF", "https://restcountries.eu/data/nfk.svg", "Ilha Norfolk", "Norfolkinsel", "Norfolk Island", "Isla de Norfolk", "جزیره نورفک", "Île de Norfolk", "Otok Norfolk", "Isola Norfolk", "ノーフォーク島", "Norfolkeiland", "Ilha Norfolk" },
                    { "KP", "https://restcountries.eu/data/prk.svg", "Coreia do Norte", "Nordkorea", "Korea (Democratic People's Republic of)", "Corea del Norte", "کره جنوبی", "Corée du Nord", "Sjeverna Koreja", "Corea del Nord", "朝鮮民主主義人民共和国", "Noord-Korea", "Coreia do Norte" },
                    { "MP", "https://restcountries.eu/data/mnp.svg", "Ilhas Marianas", "Nördliche Marianen", "Northern Mariana Islands", "Islas Marianas del Norte", "جزایر ماریانای شمالی", "Îles Mariannes du Nord", "Sjevernomarijanski otoci", "Isole Marianne Settentrionali", "北マリアナ諸島", "Noordelijke Marianeneilanden", "Ilhas Marianas" },
                    { "NO", "https://restcountries.eu/data/nor.svg", "Noruega", "Norwegen", "Norway", "Noruega", "نروژ", "Norvège", "Norveška", "Norvegia", "ノルウェー", "Noorwegen", "Noruega" },
                    { "OM", "https://restcountries.eu/data/omn.svg", "Omã", "Oman", "Oman", "Omán", "عمان", "Oman", "Oman", "oman", "オマーン", "Oman", "Omã" },
                    { "PK", "https://restcountries.eu/data/pak.svg", "Paquistão", "Pakistan", "Pakistan", "Pakistán", "پاکستان", "Pakistan", "Pakistan", "Pakistan", "パキスタン", "Pakistan", "Paquistão" },
                    { "PW", "https://restcountries.eu/data/plw.svg", "Palau", "Palau", "Palau", "Palau", "پالائو", "Palaos", "Palau", "Palau", "パラオ", "Palau", "Palau" },
                    { "PS", "https://restcountries.eu/data/pse.svg", "Palestina", "Palästina", "Palestine, State of", "Palestina", "فلسطین", "Palestine", "Palestina", "Palestina", "パレスチナ", "Palestijnse gebieden", "Palestina" },
                    { "PA", "https://restcountries.eu/data/pan.svg", "Panamá", "Panama", "Panama", "Panamá", "پاناما", "Panama", "Panama", "Panama", "パナマ", "Panama", "Panamá" },
                    { "PG", "https://restcountries.eu/data/png.svg", "Papua Nova Guiné", "Papua-Neuguinea", "Papua New Guinea", "Papúa Nueva Guinea", "پاپوآ گینه نو", "Papouasie-Nouvelle-Guinée", "Papua Nova Gvineja", "Papua Nuova Guinea", "パプアニューギニア", "Papoea-Nieuw-Guinea", "Papua Nova Guiné" },
                    { "PY", "https://restcountries.eu/data/pry.svg", "Paraguai", "Paraguay", "Paraguay", "Paraguay", "پاراگوئه", "Paraguay", "Paragvaj", "Paraguay", "パラグアイ", "Paraguay", "Paraguai" },
                    { "PE", "https://restcountries.eu/data/per.svg", "Peru", "Peru", "Peru", "Perú", "پرو", "Pérou", "Peru", "Perù", "ペルー", "Peru", "Peru" },
                    { "PH", "https://restcountries.eu/data/phl.svg", "Filipinas", "Philippinen", "Philippines", "Filipinas", "جزایر الندفیلیپین", "Philippines", "Filipini", "Filippine", "フィリピン", "Filipijnen", "Filipinas" },
                    { "PN", "https://restcountries.eu/data/pcn.svg", "Ilhas Pitcairn", "Pitcairn", "Pitcairn", "Islas Pitcairn", "پیتکرن", "Îles Pitcairn", "Pitcairnovo otočje", "Isole Pitcairn", "ピトケアン", "Pitcairneilanden", "Ilhas Picárnia" },
                    { "PL", "https://restcountries.eu/data/pol.svg", "Polônia", "Polen", "Poland", "Polonia", "لهستان", "Pologne", "Poljska", "Polonia", "ポーランド", "Polen", "Polónia" },
                    { "PT", "https://restcountries.eu/data/prt.svg", "Portugal", "Portugal", "Portugal", "Portugal", "پرتغال", "Portugal", "Portugal", "Portogallo", "ポルトガル", "Portugal", "Portugal" },
                    { "PR", "https://restcountries.eu/data/pri.svg", "Porto Rico", "Puerto Rico", "Puerto Rico", "Puerto Rico", "پورتو ریکو", "Porto Rico", "Portoriko", "Porto Rico", "プエルトリコ", "Puerto Rico", "Porto Rico" },
                    { "QA", "https://restcountries.eu/data/qat.svg", "Catar", "Katar", "Qatar", "Catar", "قطر", "Qatar", "Katar", "Qatar", "カタール", "Qatar", "Catar" },
                    { "XK", "https://restcountries.eu/data/kos.svg", "Kosovo", null, "Republic of Kosovo", "Kosovo", "کوزوو", null, "Kosovo", null, null, null, "Kosovo" },
                    { "RE", "https://restcountries.eu/data/reu.svg", "Reunião", "Réunion", "Réunion", "Reunión", "رئونیون", "Réunion", "Réunion", "Riunione", "レユニオン", "Réunion", "Reunião" },
                    { "RO", "https://restcountries.eu/data/rou.svg", "Romênia", "Rumänien", "Romania", "Rumania", "رومانی", "Roumanie", "Rumunjska", "Romania", "ルーマニア", "Roemenië", "Roménia" },
                    { "NL", "https://restcountries.eu/data/nld.svg", "Holanda", "Niederlande", "Netherlands", "Países Bajos", "پادشاهی هلند", "Pays-Bas", "Nizozemska", "Paesi Bassi", "オランダ", "Nederland", "Países Baixos" },
                    { "RU", "https://restcountries.eu/data/rus.svg", "Rússia", "Russland", "Russian Federation", "Rusia", "روسیه", "Russie", "Rusija", "Russia", "ロシア連邦", "Rusland", "Rússia" },
                    { "NP", "https://restcountries.eu/data/npl.svg", "Nepal", "Népal", "Nepal", "Nepal", "نپال", "Népal", "Nepal", "Nepal", "ネパール", "Nepal", "Nepal" },
                    { "NA", "https://restcountries.eu/data/nam.svg", "Namíbia", "Namibia", "Namibia", "Namibia", "نامیبیا", "Namibie", "Namibija", "Namibia", "ナミビア", "Namibië", "Namíbia" },
                    { "LY", "https://restcountries.eu/data/lby.svg", "Líbia", "Libyen", "Libya", "Libia", "لیبی", "Libye", "Libija", "Libia", "リビア", "Libië", "Líbia" },
                    { "LI", "https://restcountries.eu/data/lie.svg", "Liechtenstein", "Liechtenstein", "Liechtenstein", "Liechtenstein", "لیختن‌اشتاین", "Liechtenstein", "Lihtenštajn", "Liechtenstein", "リヒテンシュタイン", "Liechtenstein", "Listenstaine" },
                    { "LT", "https://restcountries.eu/data/ltu.svg", "Lituânia", "Litauen", "Lithuania", "Lituania", "لیتوانی", "Lituanie", "Litva", "Lituania", "リトアニア", "Litouwen", "Lituânia" },
                    { "LU", "https://restcountries.eu/data/lux.svg", "Luxemburgo", "Luxemburg", "Luxembourg", "Luxemburgo", "لوکزامبورگ", "Luxembourg", "Luksemburg", "Lussemburgo", "ルクセンブルク", "Luxemburg", "Luxemburgo" },
                    { "MO", "https://restcountries.eu/data/mac.svg", "Macau", "Macao", "Macao", "Macao", "مکائو", "Macao", "Makao", "Macao", "マカオ", "Macao", "Macau" },
                    { "MK", "https://restcountries.eu/data/mkd.svg", "Macedônia", "Mazedonien", "Macedonia (the former Yugoslav Republic of)", "Macedonia", "", "Macédoine", "Makedonija", "Macedonia", "マケドニア旧ユーゴスラビア共和国", "Macedonië", "Macedónia" },
                    { "MG", "https://restcountries.eu/data/mdg.svg", "Madagascar", "Madagaskar", "Madagascar", "Madagascar", "ماداگاسکار", "Madagascar", "Madagaskar", "Madagascar", "マダガスカル", "Madagaskar", "Madagáscar" },
                    { "MW", "https://restcountries.eu/data/mwi.svg", "Malawi", "Malawi", "Malawi", "Malawi", "مالاوی", "Malawi", "Malavi", "Malawi", "マラウイ", "Malawi", "Malávi" },
                    { "MY", "https://restcountries.eu/data/mys.svg", "Malásia", "Malaysia", "Malaysia", "Malasia", "مالزی", "Malaisie", "Malezija", "Malesia", "マレーシア", "Maleisië", "Malásia" },
                    { "MV", "https://restcountries.eu/data/mdv.svg", "Maldivas", "Malediven", "Maldives", "Maldivas", "مالدیو", "Maldives", "Maldivi", "Maldive", "モルディブ", "Maldiven", "Maldivas" },
                    { "ML", "https://restcountries.eu/data/mli.svg", "Mali", "Mali", "Mali", "Mali", "مالی", "Mali", "Mali", "Mali", "マリ", "Mali", "Mali" },
                    { "MT", "https://restcountries.eu/data/mlt.svg", "Malta", "Malta", "Malta", "Malta", "مالت", "Malte", "Malta", "Malta", "マルタ", "Malta", "Malta" },
                    { "MH", "https://restcountries.eu/data/mhl.svg", "Ilhas Marshall", "Marshallinseln", "Marshall Islands", "Islas Marshall", "جزایر مارشال", "Îles Marshall", "Maršalovi Otoci", "Isole Marshall", "マーシャル諸島", "Marshalleilanden", "Ilhas Marshall" },
                    { "MQ", "https://restcountries.eu/data/mtq.svg", "Martinica", "Martinique", "Martinique", "Martinica", "مونتسرات", "Martinique", "Martinique", "Martinica", "マルティニーク", "Martinique", "Martinica" },
                    { "MR", "https://restcountries.eu/data/mrt.svg", "Mauritânia", "Mauretanien", "Mauritania", "Mauritania", "موریتانی", "Mauritanie", "Mauritanija", "Mauritania", "モーリタニア", "Mauritanië", "Mauritânia" },
                    { "MU", "https://restcountries.eu/data/mus.svg", "Maurício", "Mauritius", "Mauritius", "Mauricio", "موریس", "Île Maurice", "Mauricijus", "Mauritius", "モーリシャス", "Mauritius", "Maurícia" },
                    { "YT", "https://restcountries.eu/data/myt.svg", "Mayotte", "Mayotte", "Mayotte", "Mayotte", "مایوت", "Mayotte", "Mayotte", "Mayotte", "マヨット", "Mayotte", "Mayotte" },
                    { "MX", "https://restcountries.eu/data/mex.svg", "México", "Mexiko", "Mexico", "México", "مکزیک", "Mexique", "Meksiko", "Messico", "メキシコ", "Mexico", "México" },
                    { "FM", "https://restcountries.eu/data/fsm.svg", "Micronésia", "Mikronesien", "Micronesia (Federated States of)", "Micronesia", "ایالات فدرال میکرونزی", "Micronésie", "Mikronezija", "Micronesia", "ミクロネシア連邦", "Micronesië", "Micronésia" },
                    { "MD", "https://restcountries.eu/data/mda.svg", "Moldávia", "Moldawie", "Moldova (Republic of)", "Moldavia", "مولداوی", "Moldavie", "Moldova", "Moldavia", "モルドバ共和国", "Moldavië", "Moldávia" },
                    { "MC", "https://restcountries.eu/data/mco.svg", "Mônaco", "Monaco", "Monaco", "Mónaco", "موناکو", "Monaco", "Monako", "Principato di Monaco", "モナコ", "Monaco", "Mónaco" },
                    { "MN", "https://restcountries.eu/data/mng.svg", "Mongólia", "Mongolei", "Mongolia", "Mongolia", "مغولستان", "Mongolie", "Mongolija", "Mongolia", "モンゴル", "Mongolië", "Mongólia" },
                    { "ME", "https://restcountries.eu/data/mne.svg", "Montenegro", "Montenegro", "Montenegro", "Montenegro", "مونته‌نگرو", "Monténégro", "Crna Gora", "Montenegro", "モンテネグロ", "Montenegro", "Montenegro" },
                    { "MS", "https://restcountries.eu/data/msr.svg", "Montserrat", "Montserrat", "Montserrat", "Montserrat", "مایوت", "Montserrat", "Montserrat", "Montserrat", "モントセラト", "Montserrat", "Monserrate" },
                    { "MA", "https://restcountries.eu/data/mar.svg", "Marrocos", "Marokko", "Morocco", "Marruecos", "مراکش", "Maroc", "Maroko", "Marocco", "モロッコ", "Marokko", "Marrocos" },
                    { "MZ", "https://restcountries.eu/data/moz.svg", "Moçambique", "Mosambik", "Mozambique", "Mozambique", "موزامبیک", "Mozambique", "Mozambik", "Mozambico", "モザンビーク", "Mozambique", "Moçambique" },
                    { "MM", "https://restcountries.eu/data/mmr.svg", "Myanmar", "Myanmar", "Myanmar", "Myanmar", "میانمار", "Myanmar", "Mijanmar", "Birmania", "ミャンマー", "Myanmar", "Myanmar" },
                    { "NR", "https://restcountries.eu/data/nru.svg", "Nauru", "Nauru", "Nauru", "Nauru", "نائورو", "Nauru", "Nauru", "Nauru", "ナウル", "Nauru", "Nauru" },
                    { "RW", "https://restcountries.eu/data/rwa.svg", "Ruanda", "Ruanda", "Rwanda", "Ruanda", "رواندا", "Rwanda", "Ruanda", "Ruanda", "ルワンダ", "Rwanda", "Ruanda" },
                    { "BL", "https://restcountries.eu/data/blm.svg", "São Bartolomeu", "Saint-Barthélemy", "Saint Barthélemy", "San Bartolomé", "سن-بارتلمی", "Saint-Barthélemy", "Saint Barthélemy", "Antille Francesi", "サン・バルテルミー", "Saint Barthélemy", "São Bartolomeu" },
                    { "SH", "https://restcountries.eu/data/shn.svg", "Santa Helena", "Sankt Helena", "Saint Helena, Ascension and Tristan da Cunha", "Santa Helena", "سنت هلنا، اسنشن و تریستان دا کونا", "Sainte-Hélène", "Sveta Helena", "Sant'Elena", "セントヘレナ・アセンションおよびトリスタンダクーニャ", "Sint-Helena", "Santa Helena" },
                    { "TW", "https://restcountries.eu/data/twn.svg", "Taiwan", "Taiwan", "Taiwan", "Taiwán", "تایوان", "Taïwan", "Tajvan", "Taiwan", "台湾（中華民国）", "Taiwan", "Taiwan" },
                    { "TJ", "https://restcountries.eu/data/tjk.svg", "Tajiquistão", "Tadschikistan", "Tajikistan", "Tayikistán", "تاجیکستان", "Tadjikistan", "Tađikistan", "Tagikistan", "タジキスタン", "Tadzjikistan", "Tajiquistão" },
                    { "TZ", "https://restcountries.eu/data/tza.svg", "Tanzânia", "Tansania", "Tanzania, United Republic of", "Tanzania", "تانزانیا", "Tanzanie", "Tanzanija", "Tanzania", "タンザニア", "Tanzania", "Tanzânia" },
                    { "TH", "https://restcountries.eu/data/tha.svg", "Tailândia", "Thailand", "Thailand", "Tailandia", "تایلند", "Thaïlande", "Tajland", "Tailandia", "タイ", "Thailand", "Tailândia" },
                    { "TL", "https://restcountries.eu/data/tls.svg", "Timor Leste", "Timor-Leste", "Timor-Leste", "Timor Oriental", "تیمور شرقی", "Timor oriental", "Istočni Timor", "Timor Est", "東ティモール", "Oost-Timor", "Timor Leste" },
                    { "TG", "https://restcountries.eu/data/tgo.svg", "Togo", "Togo", "Togo", "Togo", "توگو", "Togo", "Togo", "Togo", "トーゴ", "Togo", "Togo" },
                    { "TK", "https://restcountries.eu/data/tkl.svg", "Tokelau", "Tokelau", "Tokelau", "Islas Tokelau", "توکلائو", "Tokelau", "Tokelau", "Isole Tokelau", "トケラウ", "Tokelau", "Toquelau" },
                    { "TO", "https://restcountries.eu/data/ton.svg", "Tonga", "Tonga", "Tonga", "Tonga", "تونگا", "Tonga", "Tonga", "Tonga", "トンガ", "Tonga", "Tonga" },
                    { "TT", "https://restcountries.eu/data/tto.svg", "Trinidad e Tobago", "Trinidad und Tobago", "Trinidad and Tobago", "Trinidad y Tobago", "ترینیداد و توباگو", "Trinité et Tobago", "Trinidad i Tobago", "Trinidad e Tobago", "トリニダード・トバゴ", "Trinidad en Tobago", "Trindade e Tobago" },
                    { "TN", "https://restcountries.eu/data/tun.svg", "Tunísia", "Tunesien", "Tunisia", "Túnez", "تونس", "Tunisie", "Tunis", "Tunisia", "チュニジア", "Tunesië", "Tunísia" },
                    { "TR", "https://restcountries.eu/data/tur.svg", "Turquia", "Türkei", "Turkey", "Turquía", "ترکیه", "Turquie", "Turska", "Turchia", "トルコ", "Turkije", "Turquia" },
                    { "TM", "https://restcountries.eu/data/tkm.svg", "Turcomenistão", "Turkmenistan", "Turkmenistan", "Turkmenistán", "ترکمنستان", "Turkménistan", "Turkmenistan", "Turkmenistan", "トルクメニスタン", "Turkmenistan", "Turquemenistão" },
                    { "TC", "https://restcountries.eu/data/tca.svg", "Ilhas Turcas e Caicos", "Turks- und Caicosinseln", "Turks and Caicos Islands", "Islas Turks y Caicos", "جزایر تورکس و کایکوس", "Îles Turques-et-Caïques", "Otoci Turks i Caicos", "Isole Turks e Caicos", "タークス・カイコス諸島", "Turks- en Caicoseilanden", "Ilhas Turcas e Caicos" },
                    { "TV", "https://restcountries.eu/data/tuv.svg", "Tuvalu", "Tuvalu", "Tuvalu", "Tuvalu", "تووالو", "Tuvalu", "Tuvalu", "Tuvalu", "ツバル", "Tuvalu", "Tuvalu" },
                    { "UG", "https://restcountries.eu/data/uga.svg", "Uganda", "Uganda", "Uganda", "Uganda", "اوگاندا", "Uganda", "Uganda", "Uganda", "ウガンダ", "Oeganda", "Uganda" },
                    { "UA", "https://restcountries.eu/data/ukr.svg", "Ucrânia", "Ukraine", "Ukraine", "Ucrania", "وکراین", "Ukraine", "Ukrajina", "Ucraina", "ウクライナ", "Oekraïne", "Ucrânia" },
                    { "AE", "https://restcountries.eu/data/are.svg", "Emirados árabes Unidos", "Vereinigte Arabische Emirate", "United Arab Emirates", "Emiratos Árabes Unidos", "امارات متحده عربی", "Émirats arabes unis", "Ujedinjeni Arapski Emirati", "Emirati Arabi Uniti", "アラブ首長国連邦", "Verenigde Arabische Emiraten", "Emirados árabes Unidos" },
                    { "GB", "https://restcountries.eu/data/gbr.svg", "Reino Unido", "Vereinigtes Königreich", "United Kingdom of Great Britain and Northern Ireland", "Reino Unido", "بریتانیای کبیر و ایرلند شمالی", "Royaume-Uni", "Ujedinjeno Kraljevstvo", "Regno Unito", "イギリス", "Verenigd Koninkrijk", "Reino Unido" },
                    { "US", "https://restcountries.eu/data/usa.svg", "Estados Unidos", "Vereinigte Staaten von Amerika", "United States of America", "Estados Unidos", "ایالات متحده آمریکا", "États-Unis", "Sjedinjene Američke Države", "Stati Uniti D'America", "アメリカ合衆国", "Verenigde Staten", "Estados Unidos" },
                    { "UY", "https://restcountries.eu/data/ury.svg", "Uruguai", "Uruguay", "Uruguay", "Uruguay", "اروگوئه", "Uruguay", "Urugvaj", "Uruguay", "ウルグアイ", "Uruguay", "Uruguai" },
                    { "UZ", "https://restcountries.eu/data/uzb.svg", "Uzbequistão", "Usbekistan", "Uzbekistan", "Uzbekistán", "ازبکستان", "Ouzbékistan", "Uzbekistan", "Uzbekistan", "ウズベキスタン", "Oezbekistan", "Usbequistão" },
                    { "VU", "https://restcountries.eu/data/vut.svg", "Vanuatu", "Vanuatu", "Vanuatu", "Vanuatu", "وانواتو", "Vanuatu", "Vanuatu", "Vanuatu", "バヌアツ", "Vanuatu", "Vanuatu" },
                    { "VE", "https://restcountries.eu/data/ven.svg", "Venezuela", "Venezuela", "Venezuela (Bolivarian Republic of)", "Venezuela", "ونزوئلا", "Venezuela", "Venezuela", "Venezuela", "ベネズエラ・ボリバル共和国", "Venezuela", "Venezuela" },
                    { "VN", "https://restcountries.eu/data/vnm.svg", "Vietnã", "Vietnam", "Viet Nam", "Vietnam", "ویتنام", "Viêt Nam", "Vijetnam", "Vietnam", "ベトナム", "Vietnam", "Vietname" },
                    { "WF", "https://restcountries.eu/data/wlf.svg", "Wallis e Futuna", "Wallis und Futuna", "Wallis and Futuna", "Wallis y Futuna", "والیس و فوتونا", "Wallis-et-Futuna", "Wallis i Fortuna", "Wallis e Futuna", "ウォリス・フツナ", "Wallis en Futuna", "Wallis e Futuna" },
                    { "EH", "https://restcountries.eu/data/esh.svg", "Saara Ocidental", "Westsahara", "Western Sahara", "Sahara Occidental", "جمهوری دموکراتیک عربی صحرا", "Sahara Occidental", "Zapadna Sahara", "Sahara Occidentale", "西サハラ", "Westelijke Sahara", "Saara Ocidental" },
                    { "YE", "https://restcountries.eu/data/yem.svg", "Iêmen", "Jemen", "Yemen", "Yemen", "یمن", "Yémen", "Jemen", "Yemen", "イエメン", "Jemen", "Iémen" },
                    { "SY", "https://restcountries.eu/data/syr.svg", "Síria", "Syrien", "Syrian Arab Republic", "Siria", "سوریه", "Syrie", "Sirija", "Siria", "シリア・アラブ共和国", "Syrië", "Síria" },
                    { "CH", "https://restcountries.eu/data/che.svg", "Suíça", "Schweiz", "Switzerland", "Suiza", "سوئیس", "Suisse", "Švicarska", "Svizzera", "スイス", "Zwitserland", "Suíça" },
                    { "SE", "https://restcountries.eu/data/swe.svg", "Suécia", "Schweden", "Sweden", "Suecia", "سوئد", "Suède", "Švedska", "Svezia", "スウェーデン", "Zweden", "Suécia" },
                    { "SZ", "https://restcountries.eu/data/swz.svg", "Suazilândia", "Swasiland", "Swaziland", "Suazilandia", "سوازیلند", "Swaziland", "Svazi", "Swaziland", "スワジランド", "Swaziland", "Suazilândia" },
                    { "KN", "https://restcountries.eu/data/kna.svg", "São Cristóvão e Neves", "St. Kitts und Nevis", "Saint Kitts and Nevis", "San Cristóbal y Nieves", "سنت کیتس و نویس", "Saint-Christophe-et-Niévès", "Sveti Kristof i Nevis", "Saint Kitts e Nevis", "セントクリストファー・ネイビス", "Saint Kitts en Nevis", "São Cristóvão e Neves" },
                    { "LC", "https://restcountries.eu/data/lca.svg", "Santa Lúcia", "Saint Lucia", "Saint Lucia", "Santa Lucía", "سنت لوسیا", "Saint-Lucie", "Sveta Lucija", "Santa Lucia", "セントルシア", "Saint Lucia", "Santa Lúcia" },
                    { "MF", "https://restcountries.eu/data/maf.svg", "Saint Martin", "Saint Martin", "Saint Martin (French part)", "Saint Martin", "سینت مارتن", "Saint-Martin", "Sveti Martin", "Saint Martin", "サン・マルタン（フランス領）", "Saint-Martin", "Ilha São Martinho" },
                    { "PM", "https://restcountries.eu/data/spm.svg", "Saint-Pierre e Miquelon", "Saint-Pierre und Miquelon", "Saint Pierre and Miquelon", "San Pedro y Miquelón", "سن پیر و میکلن", "Saint-Pierre-et-Miquelon", "Sveti Petar i Mikelon", "Saint-Pierre e Miquelon", "サンピエール島・ミクロン島", "Saint Pierre en Miquelon", "São Pedro e Miquelon" },
                    { "VC", "https://restcountries.eu/data/vct.svg", "São Vicente e Granadinas", "Saint Vincent und die Grenadinen", "Saint Vincent and the Grenadines", "San Vicente y Granadinas", "سنت وینسنت و گرنادین‌ها", "Saint-Vincent-et-les-Grenadines", "Sveti Vincent i Grenadini", "Saint Vincent e Grenadine", "セントビンセントおよびグレナディーン諸島", "Saint Vincent en de Grenadines", "São Vicente e Granadinas" },
                    { "WS", "https://restcountries.eu/data/wsm.svg", "Samoa", "Samoa", "Samoa", "Samoa", "ساموآ", "Samoa", "Samoa", "Samoa", "サモア", "Samoa", "Samoa" },
                    { "SM", "https://restcountries.eu/data/smr.svg", "San Marino", "San Marino", "San Marino", "San Marino", "سان مارینو", "Saint-Marin", "San Marino", "San Marino", "サンマリノ", "San Marino", "São Marinho" },
                    { "ST", "https://restcountries.eu/data/stp.svg", "São Tomé e Príncipe", "São Tomé und Príncipe", "Sao Tome and Principe", "Santo Tomé y Príncipe", "کواترو دو فرویرو", "Sao Tomé-et-Principe", "Sveti Toma i Princip", "São Tomé e Príncipe", "サントメ・プリンシペ", "Sao Tomé en Principe", "São Tomé e Príncipe" },
                    { "SA", "https://restcountries.eu/data/sau.svg", "Arábia Saudita", "Saudi-Arabien", "Saudi Arabia", "Arabia Saudí", "عربستان سعودی", "Arabie Saoudite", "Saudijska Arabija", "Arabia Saudita", "サウジアラビア", "Saoedi-Arabië", "Arábia Saudita" },
                    { "SN", "https://restcountries.eu/data/sen.svg", "Senegal", "Senegal", "Senegal", "Senegal", "سنگال", "Sénégal", "Senegal", "Senegal", "セネガル", "Senegal", "Senegal" },
                    { "RS", "https://restcountries.eu/data/srb.svg", "Sérvia", "Serbien", "Serbia", "Serbia", "صربستان", "Serbie", "Srbija", "Serbia", "セルビア", "Servië", "Sérvia" },
                    { "SC", "https://restcountries.eu/data/syc.svg", "Seicheles", "Seychellen", "Seychelles", "Seychelles", "سیشل", "Seychelles", "Sejšeli", "Seychelles", "セーシェル", "Seychellen", "Seicheles" },
                    { "SL", "https://restcountries.eu/data/sle.svg", "Serra Leoa", "Sierra Leone", "Sierra Leone", "Sierra Leone", "سیرالئون", "Sierra Leone", "Sijera Leone", "Sierra Leone", "シエラレオネ", "Sierra Leone", "Serra Leoa" },
                    { "LR", "https://restcountries.eu/data/lbr.svg", "Libéria", "Liberia", "Liberia", "Liberia", "لیبریا", "Liberia", "Liberija", "Liberia", "リベリア", "Liberia", "Libéria" },
                    { "SG", "https://restcountries.eu/data/sgp.svg", "Singapura", "Singapur", "Singapore", "Singapur", "سنگاپور", "Singapour", "Singapur", "Singapore", "シンガポール", "Singapore", "Singapura" },
                    { "SK", "https://restcountries.eu/data/svk.svg", "Eslováquia", "Slowakei", "Slovakia", "República Eslovaca", "اسلواکی", "Slovaquie", "Slovačka", "Slovacchia", "スロバキア", "Slowakije", "Eslováquia" },
                    { "SI", "https://restcountries.eu/data/svn.svg", "Eslovênia", "Slowenien", "Slovenia", "Eslovenia", "اسلوونی", "Slovénie", "Slovenija", "Slovenia", "スロベニア", "Slovenië", "Eslovénia" },
                    { "SB", "https://restcountries.eu/data/slb.svg", "Ilhas Salomão", "Salomonen", "Solomon Islands", "Islas Salomón", "جزایر سلیمان", "Îles Salomon", "Solomonski Otoci", "Isole Salomone", "ソロモン諸島", "Salomonseilanden", "Ilhas Salomão" },
                    { "SO", "https://restcountries.eu/data/som.svg", "Somália", "Somalia", "Somalia", "Somalia", "سومالی", "Somalie", "Somalija", "Somalia", "ソマリア", "Somalië", "Somália" },
                    { "ZA", "https://restcountries.eu/data/zaf.svg", "República Sul-Africana", "Republik Südafrika", "South Africa", "República de Sudáfrica", "آفریقای جنوبی", "Afrique du Sud", "Južnoafrička Republika", "Sud Africa", "南アフリカ", "Zuid-Afrika", "República Sul-Africana" },
                    { "GS", "https://restcountries.eu/data/sgs.svg", "Ilhas Geórgias do Sul e Sandwich do Sul", "Südgeorgien und die Südlichen Sandwichinseln", "South Georgia and the South Sandwich Islands", "Islas Georgias del Sur y Sandwich del Sur", "جزایر جورجیای جنوبی و ساندویچ جنوبی", "Géorgie du Sud-et-les Îles Sandwich du Sud", "Južna Georgija i otočje Južni Sandwich", "Georgia del Sud e Isole Sandwich Meridionali", "サウスジョージア・サウスサンドウィッチ諸島", "Zuid-Georgia en Zuidelijke Sandwicheilanden", "Ilhas Geórgia do Sul e Sanduíche do Sul" },
                    { "KR", "https://restcountries.eu/data/kor.svg", "Coreia do Sul", "Südkorea", "Korea (Republic of)", "Corea del Sur", "کره شمالی", "Corée du Sud", "Južna Koreja", "Corea del Sud", "大韓民国", "Zuid-Korea", "Coreia do Sul" },
                    { "SS", "https://restcountries.eu/data/ssd.svg", "Sudão do Sul", "Südsudan", "South Sudan", "Sudán del Sur", "سودان جنوبی", "Soudan du Sud", "Južni Sudan", "Sudan del sud", "南スーダン", "Zuid-Soedan", "Sudão do Sul" },
                    { "ES", "https://restcountries.eu/data/esp.svg", "Espanha", "Spanien", "Spain", "España", "اسپانیا", "Espagne", "Španjolska", "Spagna", "スペイン", "Spanje", "Espanha" },
                    { "LK", "https://restcountries.eu/data/lka.svg", "Sri Lanka", "Sri Lanka", "Sri Lanka", "Sri Lanka", "سری‌لانکا", "Sri Lanka", "Šri Lanka", "Sri Lanka", "スリランカ", "Sri Lanka", "Sri Lanka" },
                    { "SD", "https://restcountries.eu/data/sdn.svg", "Sudão", "Sudan", "Sudan", "Sudán", "سودان", "Soudan", "Sudan", "Sudan", "スーダン", "Soedan", "Sudão" },
                    { "SR", "https://restcountries.eu/data/sur.svg", "Suriname", "Suriname", "Suriname", "Surinam", "سورینام", "Surinam", "Surinam", "Suriname", "スリナム", "Suriname", "Suriname" },
                    { "SJ", "https://restcountries.eu/data/sjm.svg", "Svalbard", "Svalbard und Jan Mayen", "Svalbard and Jan Mayen", "Islas Svalbard y Jan Mayen", "سوالبارد و یان ماین", "Svalbard et Jan Mayen", "Svalbard i Jan Mayen", "Svalbard e Jan Mayen", "スヴァールバル諸島およびヤンマイエン島", "Svalbard en Jan Mayen", "Svalbard" },
                    { "SX", "https://restcountries.eu/data/sxm.svg", "Sint Maarten", "Sint Maarten (niederl. Teil)", "Sint Maarten (Dutch part)", null, "سینت مارتن", "Saint Martin (partie néerlandaise)", null, "Saint Martin (parte olandese)", null, "Sint Maarten", "São Martinho" },
                    { "LS", "https://restcountries.eu/data/lso.svg", "Lesoto", "Lesotho", "Lesotho", "Lesotho", "لسوتو", "Lesotho", "Lesoto", "Lesotho", "レソト", "Lesotho", "Lesoto" },
                    { "LB", "https://restcountries.eu/data/lbn.svg", "Líbano", "Libanon", "Lebanon", "Líbano", "لبنان", "Liban", "Libanon", "Libano", "レバノン", "Libanon", "Líbano" },
                    { "LV", "https://restcountries.eu/data/lva.svg", "Letônia", "Lettland", "Latvia", "Letonia", "لتونی", "Lettonie", "Latvija", "Lettonia", "ラトビア", "Letland", "Letónia" },
                    { "UM", "https://restcountries.eu/data/umi.svg", "Ilhas Menores Distantes dos Estados Unidos", "Kleinere Inselbesitzungen der Vereinigten Staaten", "United States Minor Outlying Islands", "Islas Ultramarinas Menores de Estados Unidos", "جزایر کوچک حاشیه‌ای ایالات متحده آمریکا", "Îles mineures éloignées des États-Unis", "Mali udaljeni otoci SAD-a", "Isole minori esterne degli Stati Uniti d'America", "合衆国領有小離島", "Kleine afgelegen eilanden van de Verenigde Staten", "Ilhas Menores Distantes dos Estados Unidos" },
                    { "VG", "https://restcountries.eu/data/vgb.svg", "Ilhas Virgens Britânicas", "Britische Jungferninseln", "Virgin Islands (British)", "Islas Vírgenes del Reino Unido", "جزایر ویرجین بریتانیا", "Îles Vierges britanniques", "Britanski Djevičanski Otoci", "Isole Vergini Britanniche", "イギリス領ヴァージン諸島", "Britse Maagdeneilanden", "Ilhas Virgens Britânicas" },
                    { "VI", "https://restcountries.eu/data/vir.svg", "Ilhas Virgens Americanas", "Amerikanische Jungferninseln", "Virgin Islands (U.S.)", "Islas Vírgenes de los Estados Unidos", "جزایر ویرجین آمریکا", "Îles Vierges des États-Unis", null, "Isole Vergini americane", "アメリカ領ヴァージン諸島", "Verenigde Staten Maagdeneilanden", "Ilhas Virgens Americanas" },
                    { "BN", "https://restcountries.eu/data/brn.svg", "Brunei", "Brunei", "Brunei Darussalam", "Brunei", "برونئی", "Brunei", "Brunej", "Brunei", "ブルネイ・ダルサラーム", "Brunei", "Brunei" },
                    { "BG", "https://restcountries.eu/data/bgr.svg", "Bulgária", "Bulgarien", "Bulgaria", "Bulgaria", "بلغارستان", "Bulgarie", "Bugarska", "Bulgaria", "ブルガリア", "Bulgarije", "Bulgária" },
                    { "BF", "https://restcountries.eu/data/bfa.svg", "Burkina Faso", "Burkina Faso", "Burkina Faso", "Burkina Faso", "بورکینافاسو", "Burkina Faso", "Burkina Faso", "Burkina Faso", "ブルキナファソ", "Burkina Faso", "Burquina Faso" },
                    { "BI", "https://restcountries.eu/data/bdi.svg", "Burundi", "Burundi", "Burundi", "Burundi", "بوروندی", "Burundi", "Burundi", "Burundi", "ブルンジ", "Burundi", "Burúndi" },
                    { "KH", "https://restcountries.eu/data/khm.svg", "Camboja", "Kambodscha", "Cambodia", "Camboya", "کامبوج", "Cambodge", "Kambodža", "Cambogia", "カンボジア", "Cambodja", "Camboja" },
                    { "CM", "https://restcountries.eu/data/cmr.svg", "Camarões", "Kamerun", "Cameroon", "Camerún", "کامرون", "Cameroun", "Kamerun", "Camerun", "カメルーン", "Kameroen", "Camarões" },
                    { "CA", "https://restcountries.eu/data/can.svg", "Canadá", "Kanada", "Canada", "Canadá", "کانادا", "Canada", "Kanada", "Canada", "カナダ", "Canada", "Canadá" },
                    { "CV", "https://restcountries.eu/data/cpv.svg", "Cabo Verde", "Kap Verde", "Cabo Verde", "Cabo Verde", "کیپ ورد", "Cap Vert", "Zelenortska Republika", "Capo Verde", "カーボベルデ", "Kaapverdië", "Cabo Verde" },
                    { "KY", "https://restcountries.eu/data/cym.svg", "Ilhas Cayman", "Kaimaninseln", "Cayman Islands", "Islas Caimán", "جزایر کیمن", "Îles Caïmans", "Kajmanski otoci", "Isole Cayman", "ケイマン諸島", "Caymaneilanden", "Ilhas Caimão" },
                    { "CF", "https://restcountries.eu/data/caf.svg", "República Centro-Africana", "Zentralafrikanische Republik", "Central African Republic", "República Centroafricana", "جمهوری آفریقای مرکزی", "République centrafricaine", "Srednjoafrička Republika", "Repubblica Centrafricana", "中央アフリカ共和国", "Centraal-Afrikaanse Republiek", "República Centro-Africana" },
                    { "TD", "https://restcountries.eu/data/tcd.svg", "Chade", "Tschad", "Chad", "Chad", "چاد", "Tchad", "Čad", "Ciad", "チャド", "Tsjaad", "Chade" },
                    { "CL", "https://restcountries.eu/data/chl.svg", "Chile", "Chile", "Chile", "Chile", "شیلی", "Chili", "Čile", "Cile", "チリ", "Chili", "Chile" },
                    { "CN", "https://restcountries.eu/data/chn.svg", "China", "China", "China", "China", "چین", "Chine", "Kina", "Cina", "中国", "China", "China" },
                    { "CX", "https://restcountries.eu/data/cxr.svg", "Ilha Christmas", "Weihnachtsinsel", "Christmas Island", "Isla de Navidad", "جزیره کریسمس", "Île Christmas", "Božićni otok", "Isola di Natale", "クリスマス島", "Christmaseiland", "Ilha do Natal" },
                    { "CC", "https://restcountries.eu/data/cck.svg", "Ilhas Cocos", "Kokosinseln", "Cocos (Keeling) Islands", "Islas Cocos o Islas Keeling", "جزایر کوکوس", "Îles Cocos", "Kokosovi Otoci", "Isole Cocos e Keeling", "ココス（キーリング）諸島", "Cocoseilanden", "Ilhas dos Cocos" },
                    { "CO", "https://restcountries.eu/data/col.svg", "Colômbia", "Kolumbien", "Colombia", "Colombia", "کلمبیا", "Colombie", "Kolumbija", "Colombia", "コロンビア", "Colombia", "Colômbia" },
                    { "KM", "https://restcountries.eu/data/com.svg", "Comores", "Union der Komoren", "Comoros", "Comoras", "کومور", "Comores", "Komori", "Comore", "コモロ", "Comoren", "Comores" },
                    { "CG", "https://restcountries.eu/data/cog.svg", "Congo", "Kongo", "Congo", "Congo", "کنگو", "Congo", "Kongo", "Congo", "コンゴ共和国", "Congo [Republiek]", "Congo" },
                    { "CD", "https://restcountries.eu/data/cod.svg", "RD Congo", "Kongo (Dem. Rep.)", "Congo (Democratic Republic of the)", "Congo (Rep. Dem.)", "جمهوری کنگو", "Congo (Rép. dém.)", "Kongo, Demokratska Republika", "Congo (Rep. Dem.)", "コンゴ民主共和国", "Congo [DRC]", "RD Congo" },
                    { "CK", "https://restcountries.eu/data/cok.svg", "Ilhas Cook", "Cookinseln", "Cook Islands", "Islas Cook", "جزایر کوک", "Îles Cook", "Cookovo Otočje", "Isole Cook", "クック諸島", "Cookeilanden", "Ilhas Cook" },
                    { "CR", "https://restcountries.eu/data/cri.svg", "Costa Rica", "Costa Rica", "Costa Rica", "Costa Rica", "کاستاریکا", "Costa Rica", "Kostarika", "Costa Rica", "コスタリカ", "Costa Rica", "Costa Rica" },
                    { "HR", "https://restcountries.eu/data/hrv.svg", "Croácia", "Kroatien", "Croatia", "Croacia", "کرواسی", "Croatie", "Hrvatska", "Croazia", "クロアチア", "Kroatië", "Croácia" },
                    { "CU", "https://restcountries.eu/data/cub.svg", "Cuba", "Kuba", "Cuba", "Cuba", "کوبا", "Cuba", "Kuba", "Cuba", "キューバ", "Cuba", "Cuba" },
                    { "CW", "https://restcountries.eu/data/cuw.svg", "Curaçao", "Curaçao", "Curaçao", null, "کوراسائو", "Curaçao", null, "Curaçao", null, "Curaçao", "Curaçao" },
                    { "IO", "https://restcountries.eu/data/iot.svg", "Território Britânico do Oceano íÍdico", "Britisches Territorium im Indischen Ozean", "British Indian Ocean Territory", "Territorio Británico del Océano Índico", "قلمرو بریتانیا در اقیانوس هند", "Territoire britannique de l'océan Indien", "Britanski Indijskooceanski teritorij", "Territorio britannico dell'oceano indiano", "イギリス領インド洋地域", "Britse Gebieden in de Indische Oceaan", "Território Britânico do Oceano Índico" },
                    { "BR", "https://restcountries.eu/data/bra.svg", "Brasil", "Brasilien", "Brazil", "Brasil", "برزیل", "Brésil", "Brazil", "Brasile", "ブラジル", "Brazilië", "Brasil" },
                    { "BV", "https://restcountries.eu/data/bvt.svg", "Ilha Bouvet", "Bouvetinsel", "Bouvet Island", "Isla Bouvet", "جزیره بووه", "Île Bouvet", "Otok Bouvet", "Isola Bouvet", "ブーベ島", "Bouveteiland", "Ilha Bouvet" },
                    { "BW", "https://restcountries.eu/data/bwa.svg", "Botsuana", "Botswana", "Botswana", "Botswana", "بوتسوانا", "Botswana", "Bocvana", "Botswana", "ボツワナ", "Botswana", "Botsuana" },
                    { "AX", "https://restcountries.eu/data/ala.svg", "Ilhas de Aland", "Åland", "Åland Islands", "Alandia", "جزایر الند", "Åland", "Ålandski otoci", "Isole Aland", "オーランド諸島", "Ålandeilanden", "Ilhas de Aland" },
                    { "AL", "https://restcountries.eu/data/alb.svg", "Albânia", "Albanien", "Albania", "Albania", "آلبانی", "Albanie", "Albanija", "Albania", "アルバニア", "Albanië", "Albânia" },
                    { "DZ", "https://restcountries.eu/data/dza.svg", "Argélia", "Algerien", "Algeria", "Argelia", "الجزایر", "Algérie", "Alžir", "Algeria", "アルジェリア", "Algerije", "Argélia" },
                    { "AS", "https://restcountries.eu/data/asm.svg", "Samoa Americana", "Amerikanisch-Samoa", "American Samoa", "Samoa Americana", "ساموآی آمریکا", "Samoa américaines", "Američka Samoa", "Samoa Americane", "アメリカ領サモア", "Amerikaans Samoa", "Samoa Americana" }
                });

            migrationBuilder.InsertData(
                table: "Countries",
                columns: new[] { "Code", "Flag", "NameBR", "NameDE", "NameEN", "NameES", "NameFA", "NameFR", "NameHR", "NameIT", "NameJA", "NameNL", "NamePT" },
                values: new object[,]
                {
                    { "AD", "https://restcountries.eu/data/and.svg", "Andorra", "Andorra", "Andorra", "Andorra", "آندورا", "Andorre", "Andora", "Andorra", "アンドラ", "Andorra", "Andorra" },
                    { "AO", "https://restcountries.eu/data/ago.svg", "Angola", "Angola", "Angola", "Angola", "آنگولا", "Angola", "Angola", "Angola", "アンゴラ", "Angola", "Angola" },
                    { "AI", "https://restcountries.eu/data/aia.svg", "Anguila", "Anguilla", "Anguilla", "Anguilla", "آنگویلا", "Anguilla", "Angvila", "Anguilla", "アンギラ", "Anguilla", "Anguila" },
                    { "AQ", "https://restcountries.eu/data/ata.svg", "Antártida", "Antarktika", "Antarctica", "Antártida", "جنوبگان", "Antarctique", "Antarktika", "Antartide", "南極大陸", "Antarctica", "Antárctida" },
                    { "AG", "https://restcountries.eu/data/atg.svg", "Antígua e Barbuda", "Antigua und Barbuda", "Antigua and Barbuda", "Antigua y Barbuda", "آنتیگوا و باربودا", "Antigua-et-Barbuda", "Antigva i Barbuda", "Antigua e Barbuda", "アンティグア・バーブーダ", "Antigua en Barbuda", "Antígua e Barbuda" },
                    { "AR", "https://restcountries.eu/data/arg.svg", "Argentina", "Argentinien", "Argentina", "Argentina", "آرژانتین", "Argentine", "Argentina", "Argentina", "アルゼンチン", "Argentinië", "Argentina" },
                    { "AM", "https://restcountries.eu/data/arm.svg", "Armênia", "Armenien", "Armenia", "Armenia", "ارمنستان", "Arménie", "Armenija", "Armenia", "アルメニア", "Armenië", "Arménia" },
                    { "AW", "https://restcountries.eu/data/abw.svg", "Aruba", "Aruba", "Aruba", "Aruba", "آروبا", "Aruba", "Aruba", "Aruba", "アルバ", "Aruba", "Aruba" },
                    { "AU", "https://restcountries.eu/data/aus.svg", "Austrália", "Australien", "Australia", "Australia", "استرالیا", "Australie", "Australija", "Australia", "オーストラリア", "Australië", "Austrália" },
                    { "CY", "https://restcountries.eu/data/cyp.svg", "Chipre", "Zypern", "Cyprus", "Chipre", "قبرس", "Chypre", "Cipar", "Cipro", "キプロス", "Cyprus", "Chipre" },
                    { "AT", "https://restcountries.eu/data/aut.svg", "áustria", "Österreich", "Austria", "Austria", "اتریش", "Autriche", "Austrija", "Austria", "オーストリア", "Oostenrijk", "áustria" },
                    { "BS", "https://restcountries.eu/data/bhs.svg", "Bahamas", "Bahamas", "Bahamas", "Bahamas", "باهاما", "Bahamas", "Bahami", "Bahamas", "バハマ", "Bahama’s", "Baamas" },
                    { "BH", "https://restcountries.eu/data/bhr.svg", "Bahrein", "Bahrain", "Bahrain", "Bahrein", "بحرین", "Bahreïn", "Bahrein", "Bahrein", "バーレーン", "Bahrein", "Barém" },
                    { "BD", "https://restcountries.eu/data/bgd.svg", "Bangladesh", "Bangladesch", "Bangladesh", "Bangladesh", "بنگلادش", "Bangladesh", "Bangladeš", "Bangladesh", "バングラデシュ", "Bangladesh", "Bangladeche" },
                    { "BB", "https://restcountries.eu/data/brb.svg", "Barbados", "Barbados", "Barbados", "Barbados", "باربادوس", "Barbade", "Barbados", "Barbados", "バルバドス", "Barbados", "Barbados" },
                    { "BY", "https://restcountries.eu/data/blr.svg", "Bielorrússia", "Weißrussland", "Belarus", "Bielorrusia", "بلاروس", "Biélorussie", "Bjelorusija", "Bielorussia", "ベラルーシ", "Wit-Rusland", "Bielorrússia" },
                    { "BE", "https://restcountries.eu/data/bel.svg", "Bélgica", "Belgien", "Belgium", "Bélgica", "بلژیک", "Belgique", "Belgija", "Belgio", "ベルギー", "België", "Bélgica" },
                    { "BZ", "https://restcountries.eu/data/blz.svg", "Belize", "Belize", "Belize", "Belice", "بلیز", "Belize", "Belize", "Belize", "ベリーズ", "Belize", "Belize" },
                    { "BJ", "https://restcountries.eu/data/ben.svg", "Benin", "Benin", "Benin", "Benín", "بنین", "Bénin", "Benin", "Benin", "ベナン", "Benin", "Benim" },
                    { "BM", "https://restcountries.eu/data/bmu.svg", "Bermudas", "Bermuda", "Bermuda", "Bermudas", "برمودا", "Bermudes", "Bermudi", "Bermuda", "バミューダ", "Bermuda", "Bermudas" },
                    { "BT", "https://restcountries.eu/data/btn.svg", "Butão", "Bhutan", "Bhutan", "Bután", "بوتان", "Bhoutan", "Butan", "Bhutan", "ブータン", "Bhutan", "Butão" },
                    { "BO", "https://restcountries.eu/data/bol.svg", "Bolívia", "Bolivien", "Bolivia (Plurinational State of)", "Bolivia", "بولیوی", "Bolivie", "Bolivija", "Bolivia", "ボリビア多民族国", "Bolivia", "Bolívia" },
                    { "BQ", "https://restcountries.eu/data/bes.svg", "Bonaire", "Bonaire, Sint Eustatius und Saba", "Bonaire, Sint Eustatius and Saba", null, "بونیر", "Bonaire, Saint-Eustache et Saba", null, "Bonaire, Saint-Eustache e Saba", null, null, "Bonaire" },
                    { "BA", "https://restcountries.eu/data/bih.svg", "Bósnia e Herzegovina", "Bosnien und Herzegowina", "Bosnia and Herzegovina", "Bosnia y Herzegovina", "بوسنی و هرزگوین", "Bosnie-Herzégovine", "Bosna i Hercegovina", "Bosnia ed Erzegovina", "ボスニア・ヘルツェゴビナ", "Bosnië en Herzegovina", "Bósnia e Herzegovina" },
                    { "AZ", "https://restcountries.eu/data/aze.svg", "Azerbaijão", "Aserbaidschan", "Azerbaijan", "Azerbaiyán", "آذربایجان", "Azerbaïdjan", "Azerbajdžan", "Azerbaijan", "アゼルバイジャン", "Azerbeidzjan", "Azerbaijão" },
                    { "ZM", "https://restcountries.eu/data/zmb.svg", "Zâmbia", "Sambia", "Zambia", "Zambia", "زامبیا", "Zambie", "Zambija", "Zambia", "ザンビア", "Zambia", "Zâmbia" },
                    { "CZ", "https://restcountries.eu/data/cze.svg", "República Tcheca", "Tschechische Republik", "Czech Republic", "República Checa", "جمهوری چک", "République tchèque", "Češka", "Repubblica Ceca", "チェコ", "Tsjechië", "República Checa" },
                    { "DJ", "https://restcountries.eu/data/dji.svg", "Djibuti", "Dschibuti", "Djibouti", "Yibuti", "جیبوتی", "Djibouti", "Džibuti", "Gibuti", "ジブチ", "Djibouti", "Djibuti" },
                    { "GY", "https://restcountries.eu/data/guy.svg", "Guiana", "Guyana", "Guyana", "Guyana", "گویان", "Guyane", "Gvajana", "Guyana", "ガイアナ", "Guyana", "Guiana" },
                    { "HT", "https://restcountries.eu/data/hti.svg", "Haiti", "Haiti", "Haiti", "Haiti", "هائیتی", "Haïti", "Haiti", "Haiti", "ハイチ", "Haïti", "Haiti" },
                    { "HM", "https://restcountries.eu/data/hmd.svg", "Ilha Heard e Ilhas McDonald", "Heard und die McDonaldinseln", "Heard Island and McDonald Islands", "Islas Heard y McDonald", "جزیره هرد و جزایر مک‌دونالد", "Îles Heard-et-MacDonald", "Otok Heard i otočje McDonald", "Isole Heard e McDonald", "ハード島とマクドナルド諸島", "Heard- en McDonaldeilanden", "Ilha Heard e Ilhas McDonald" },
                    { "VA", "https://restcountries.eu/data/vat.svg", "Vaticano", "Heiliger Stuhl", "Holy See", "Santa Sede", "سریر مقدس", "voir Saint", "Sveta Stolica", "Santa Sede", "聖座", "Heilige Stoel", "Vaticano" },
                    { "HN", "https://restcountries.eu/data/hnd.svg", "Honduras", "Honduras", "Honduras", "Honduras", "هندوراس", "Honduras", "Honduras", "Honduras", "ホンジュラス", "Honduras", "Honduras" },
                    { "HK", "https://restcountries.eu/data/hkg.svg", "Hong Kong", "Hong Kong", "Hong Kong", "Hong Kong", "هنگ‌کنگ", "Hong Kong", "Hong Kong", "Hong Kong", "香港", "Hongkong", "Hong Kong" },
                    { "HU", "https://restcountries.eu/data/hun.svg", "Hungria", "Ungarn", "Hungary", "Hungría", "مجارستان", "Hongrie", "Mađarska", "Ungheria", "ハンガリー", "Hongarije", "Hungria" },
                    { "IS", "https://restcountries.eu/data/isl.svg", "Islândia", "Island", "Iceland", "Islandia", "ایسلند", "Islande", "Island", "Islanda", "アイスランド", "IJsland", "Islândia" },
                    { "IN", "https://restcountries.eu/data/ind.svg", "Índia", "Indien", "India", "India", "هند", "Inde", "Indija", "India", "インド", "India", "Índia" },
                    { "ID", "https://restcountries.eu/data/idn.svg", "Indonésia", "Indonesien", "Indonesia", "Indonesia", "اندونزی", "Indonésie", "Indonezija", "Indonesia", "インドネシア", "Indonesië", "Indonésia" },
                    { "CI", "https://restcountries.eu/data/civ.svg", "Costa do Marfim", "Elfenbeinküste", "Côte d'Ivoire", "Costa de Marfil", "ساحل عاج", "Côte d'Ivoire", "Obala Bjelokosti", "Costa D'Avorio", "コートジボワール", "Ivoorkust", "Costa do Marfim" },
                    { "IR", "https://restcountries.eu/data/irn.svg", "Irã", "Iran", "Iran (Islamic Republic of)", "Iran", "ایران", "Iran", "Iran", null, "イラン・イスラム共和国", "Iran", "Irão" },
                    { "IQ", "https://restcountries.eu/data/irq.svg", "Iraque", "Irak", "Iraq", "Irak", "عراق", "Irak", "Irak", "Iraq", "イラク", "Irak", "Iraque" },
                    { "IE", "https://restcountries.eu/data/irl.svg", "Irlanda", "Irland", "Ireland", "Irlanda", "ایرلند", "Irlande", "Irska", "Irlanda", "アイルランド", "Ierland", "Irlanda" },
                    { "IM", "https://restcountries.eu/data/imn.svg", "Ilha de Man", "Insel Man", "Isle of Man", "Isla de Man", "جزیره من", "Île de Man", "Otok Man", "Isola di Man", "マン島", "Isle of Man", "Ilha de Man" },
                    { "IL", "https://restcountries.eu/data/isr.svg", "Israel", "Israel", "Israel", "Israel", "اسرائیل", "Israël", "Izrael", "Israele", "イスラエル", "Israël", "Israel" },
                    { "IT", "https://restcountries.eu/data/ita.svg", "Itália", "Italien", "Italy", "Italia", "ایتالیا", "Italie", "Italija", "Italia", "イタリア", "Italië", "Itália" },
                    { "JM", "https://restcountries.eu/data/jam.svg", "Jamaica", "Jamaika", "Jamaica", "Jamaica", "جامائیکا", "Jamaïque", "Jamajka", "Giamaica", "ジャマイカ", "Jamaica", "Jamaica" },
                    { "JP", "https://restcountries.eu/data/jpn.svg", "Japão", "Japan", "Japan", "Japón", "ژاپن", "Japon", "Japan", "Giappone", "日本", "Japan", "Japão" },
                    { "JE", "https://restcountries.eu/data/jey.svg", "Jersey", "Jersey", "Jersey", "Jersey", "جرزی", "Jersey", "Jersey", "Isola di Jersey", "ジャージー", "Jersey", "Jersey" },
                    { "JO", "https://restcountries.eu/data/jor.svg", "Jordânia", "Jordanien", "Jordan", "Jordania", "اردن", "Jordanie", "Jordan", "Giordania", "ヨルダン", "Jordanië", "Jordânia" },
                    { "KZ", "https://restcountries.eu/data/kaz.svg", "Cazaquistão", "Kasachstan", "Kazakhstan", "Kazajistán", "قزاقستان", "Kazakhstan", "Kazahstan", "Kazakistan", "カザフスタン", "Kazachstan", "Cazaquistão" },
                    { "KE", "https://restcountries.eu/data/ken.svg", "Quênia", "Kenia", "Kenya", "Kenia", "کنیا", "Kenya", "Kenija", "Kenya", "ケニア", "Kenia", "Quénia" },
                    { "KI", "https://restcountries.eu/data/kir.svg", "Kiribati", "Kiribati", "Kiribati", "Kiribati", "کیریباتی", "Kiribati", "Kiribati", "Kiribati", "キリバス", "Kiribati", "Quiribáti" },
                    { "KW", "https://restcountries.eu/data/kwt.svg", "Kuwait", "Kuwait", "Kuwait", "Kuwait", "کویت", "Koweït", "Kuvajt", "Kuwait", "クウェート", "Koeweit", "Kuwait" },
                    { "KG", "https://restcountries.eu/data/kgz.svg", "Quirguistão", "Kirgisistan", "Kyrgyzstan", "Kirguizistán", "قرقیزستان", "Kirghizistan", "Kirgistan", "Kirghizistan", "キルギス", "Kirgizië", "Quirguizistão" },
                    { "LA", "https://restcountries.eu/data/lao.svg", "Laos", "Laos", "Lao People's Democratic Republic", "Laos", "لائوس", "Laos", "Laos", "Laos", "ラオス人民民主共和国", "Laos", "Laos" },
                    { "GW", "https://restcountries.eu/data/gnb.svg", "Guiné-Bissau", "Guinea-Bissau", "Guinea-Bissau", "Guinea-Bisáu", "گینه بیسائو", "Guinée-Bissau", "Gvineja Bisau", "Guinea-Bissau", "ギニアビサウ", "Guinee-Bissau", "Guiné-Bissau" },
                    { "GN", "https://restcountries.eu/data/gin.svg", "Guiné", "Guinea", "Guinea", "Guinea", "گینه", "Guinée", "Gvineja", "Guinea", "ギニア", "Guinee", "Guiné" },
                    { "GG", "https://restcountries.eu/data/ggy.svg", "Guernsey", "Guernsey", "Guernsey", "Guernsey", "گرنزی", "Guernesey", "Guernsey", "Guernsey", "ガーンジー", "Guernsey", "Guernsey" },
                    { "GT", "https://restcountries.eu/data/gtm.svg", "Guatemala", "Guatemala", "Guatemala", "Guatemala", "گواتمالا", "Guatemala", "Gvatemala", "Guatemala", "グアテマラ", "Guatemala", "Guatemala" },
                    { "DM", "https://restcountries.eu/data/dma.svg", "Dominica", "Dominica", "Dominica", "Dominica", "دومینیکا", "Dominique", "Dominika", "Dominica", "ドミニカ国", "Dominica", "Dominica" },
                    { "DO", "https://restcountries.eu/data/dom.svg", "República Dominicana", "Dominikanische Republik", "Dominican Republic", "República Dominicana", "جمهوری دومینیکن", "République dominicaine", "Dominikanska Republika", "Repubblica Dominicana", "ドミニカ共和国", "Dominicaanse Republiek", "República Dominicana" },
                    { "EC", "https://restcountries.eu/data/ecu.svg", "Equador", "Ecuador", "Ecuador", "Ecuador", "اکوادور", "Équateur", "Ekvador", "Ecuador", "エクアドル", "Ecuador", "Equador" },
                    { "EG", "https://restcountries.eu/data/egy.svg", "Egito", "Ägypten", "Egypt", "Egipto", "مصر", "Égypte", "Egipat", "Egitto", "エジプト", "Egypte", "Egipto" },
                    { "SV", "https://restcountries.eu/data/slv.svg", "El Salvador", "El Salvador", "El Salvador", "El Salvador", "السالوادور", "Salvador", "Salvador", "El Salvador", "エルサルバドル", "El Salvador", "El Salvador" },
                    { "GQ", "https://restcountries.eu/data/gnq.svg", "Guiné Equatorial", "Äquatorial-Guinea", "Equatorial Guinea", "Guinea Ecuatorial", "گینه استوایی", "Guinée-Équatoriale", "Ekvatorijalna Gvineja", "Guinea Equatoriale", "赤道ギニア", "Equatoriaal-Guinea", "Guiné Equatorial" },
                    { "ER", "https://restcountries.eu/data/eri.svg", "Eritreia", "Eritrea", "Eritrea", "Eritrea", "اریتره", "Érythrée", "Eritreja", "Eritrea", "エリトリア", "Eritrea", "Eritreia" },
                    { "EE", "https://restcountries.eu/data/est.svg", "Estônia", "Estland", "Estonia", "Estonia", "استونی", "Estonie", "Estonija", "Estonia", "エストニア", "Estland", "Estónia" },
                    { "ET", "https://restcountries.eu/data/eth.svg", "Etiópia", "Äthiopien", "Ethiopia", "Etiopía", "اتیوپی", "Éthiopie", "Etiopija", "Etiopia", "エチオピア", "Ethiopië", "Etiópia" },
                    { "FK", "https://restcountries.eu/data/flk.svg", "Ilhas Malvinas", "Falklandinseln", "Falkland Islands (Malvinas)", "Islas Malvinas", "جزایر فالکلند", "Îles Malouines", "Falklandski Otoci", "Isole Falkland o Isole Malvine", "フォークランド（マルビナス）諸島", "Falklandeilanden [Islas Malvinas]", "Ilhas Falkland" },
                    { "FO", "https://restcountries.eu/data/fro.svg", "Ilhas Faroé", "Färöer-Inseln", "Faroe Islands", "Islas Faroe", "جزایر فارو", "Îles Féroé", "Farski Otoci", "Isole Far Oer", "フェロー諸島", "Faeröer", "Ilhas Faroé" },
                    { "FJ", "https://restcountries.eu/data/fji.svg", "Fiji", "Fidschi", "Fiji", "Fiyi", "فیجی", "Fidji", "Fiđi", "Figi", "フィジー", "Fiji", "Fiji" },
                    { "FI", "https://restcountries.eu/data/fin.svg", "Finlândia", "Finnland", "Finland", "Finlandia", "فنلاند", "Finlande", "Finska", "Finlandia", "フィンランド", "Finland", "Finlândia" },
                    { "DK", "https://restcountries.eu/data/dnk.svg", "Dinamarca", "Dänemark", "Denmark", "Dinamarca", "دانمارک", "Danemark", "Danska", "Danimarca", "デンマーク", "Denemarken", "Dinamarca" },
                    { "FR", "https://restcountries.eu/data/fra.svg", "França", "Frankreich", "France", "Francia", "فرانسه", "France", "Francuska", "Francia", "フランス", "Frankrijk", "França" },
                    { "PF", "https://restcountries.eu/data/pyf.svg", "Polinésia Francesa", "Französisch-Polynesien", "French Polynesia", "Polinesia Francesa", "پلی‌نزی فرانسه", "Polynésie française", "Francuska Polinezija", "Polinesia Francese", "フランス領ポリネシア", "Frans-Polynesië", "Polinésia Francesa" },
                    { "TF", "https://restcountries.eu/data/atf.svg", "Terras Austrais e Antárticas Francesas", "Französische Süd- und Antarktisgebiete", "French Southern Territories", "Tierras Australes y Antárticas Francesas", "سرزمین‌های جنوبی و جنوبگانی فرانسه", "Terres australes et antarctiques françaises", "Francuski južni i antarktički teritoriji", "Territori Francesi del Sud", "フランス領南方・南極地域", "Franse Gebieden in de zuidelijke Indische Oceaan", "Terras Austrais e Antárticas Francesas" },
                    { "GA", "https://restcountries.eu/data/gab.svg", "Gabão", "Gabun", "Gabon", "Gabón", "گابن", "Gabon", "Gabon", "Gabon", "ガボン", "Gabon", "Gabão" },
                    { "GM", "https://restcountries.eu/data/gmb.svg", "Gâmbia", "Gambia", "Gambia", "Gambia", "گامبیا", "Gambie", "Gambija", "Gambia", "ガンビア", "Gambia", "Gâmbia" },
                    { "GE", "https://restcountries.eu/data/geo.svg", "Geórgia", "Georgien", "Georgia", "Georgia", "گرجستان", "Géorgie", "Gruzija", "Georgia", "グルジア", "Georgië", "Geórgia" },
                    { "DE", "https://restcountries.eu/data/deu.svg", "Alemanha", "Deutschland", "Germany", "Alemania", "آلمان", "Allemagne", "Njemačka", "Germania", "ドイツ", "Duitsland", "Alemanha" },
                    { "GH", "https://restcountries.eu/data/gha.svg", "Gana", "Ghana", "Ghana", "Ghana", "غنا", "Ghana", "Gana", "Ghana", "ガーナ", "Ghana", "Gana" },
                    { "GI", "https://restcountries.eu/data/gib.svg", "Gibraltar", "Gibraltar", "Gibraltar", "Gibraltar", "جبل‌طارق", "Gibraltar", "Gibraltar", "Gibilterra", "ジブラルタル", "Gibraltar", "Gibraltar" },
                    { "GR", "https://restcountries.eu/data/grc.svg", "Grécia", "Griechenland", "Greece", "Grecia", "یونان", "Grèce", "Grčka", "Grecia", "ギリシャ", "Griekenland", "Grécia" },
                    { "GL", "https://restcountries.eu/data/grl.svg", "Groelândia", "Grönland", "Greenland", "Groenlandia", "گرینلند", "Groenland", "Grenland", "Groenlandia", "グリーンランド", "Groenland", "Gronelândia" },
                    { "GD", "https://restcountries.eu/data/grd.svg", "Granada", "Grenada", "Grenada", "Grenada", "گرنادا", "Grenade", "Grenada", "Grenada", "グレナダ", "Grenada", "Granada" },
                    { "GP", "https://restcountries.eu/data/glp.svg", "Guadalupe", "Guadeloupe", "Guadeloupe", "Guadalupe", "جزیره گوادلوپ", "Guadeloupe", "Gvadalupa", "Guadeloupa", "グアドループ", "Guadeloupe", "Guadalupe" },
                    { "GU", "https://restcountries.eu/data/gum.svg", "Guam", "Guam", "Guam", "Guam", "گوام", "Guam", "Guam", "Guam", "グアム", "Guam", "Guame" },
                    { "GF", "https://restcountries.eu/data/guf.svg", "Guiana Francesa", "Französisch Guyana", "French Guiana", "Guayana Francesa", "گویان فرانسه", "Guayane", "Francuska Gvajana", "Guyana francese", "フランス領ギアナ", "Frans-Guyana", "Guiana Francesa" },
                    { "ZW", "https://restcountries.eu/data/zwe.svg", "Zimbabwe", "Simbabwe", "Zimbabwe", "Zimbabue", "زیمباوه", "Zimbabwe", "Zimbabve", "Zimbabwe", "ジンバブエ", "Zimbabwe", "Zimbabué" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Stations_CountryCode",
                table: "Stations",
                column: "CountryCode");

            migrationBuilder.AddForeignKey(
                name: "FK_Stations_Countries_CountryCode",
                table: "Stations",
                column: "CountryCode",
                principalTable: "Countries",
                principalColumn: "Code",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Stations_Countries_CountryCode",
                table: "Stations");

            migrationBuilder.DropTable(
                name: "Countries");

            migrationBuilder.DropIndex(
                name: "IX_Stations_CountryCode",
                table: "Stations");
        }
    }
}
